namespace: devops-lab

postgres:
replicas: 1

image:
repository: postgres
tag: "16"

auth:
username: admin
password: admin123
database: devopslab

storage: 2Gi

service:
type: ClusterIP
port: 5432

backend:
replicas: 1

resources:
requests:
cpu: 100m
memory: 128Mi
limits:
cpu: 500m
memory: 512Mi

image:
repository: host.docker.internal/devops-lab/backend
tag: 24
pullPolicy: Always

service:
type: ClusterIP
port: 5000

database:
host: postgres
port: "5432"

frontend:
replicas: 1

image:
repository: host.docker.internal/devops-lab/frontend
tag: 24
pullPolicy: Always

service:
type: ClusterIP
port: 80

ingress:
enabled: true
className: nginx

host: devops-lab.local

frontend:
path: /

backend:
path: /api
